### ISSUE TITLE
Define Data Lake storage structure and mandatory dataset content

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#10]
### Task description

Define mandatory dataset content and storage structure for the data lake, so that we can starting building user stories that won't need to be changed or redone later.

#### Acceptance Criteria

- [x] We understand what minimum metadata and data content we need to have well managed data lake
- [x] Design document describing the data and metadata storage and content ready to demo to users

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
