### ISSUE TITLE
Import data and metadata - 'LINZ Developer' User Mapping

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#11]
### Task

To complete #18 and #23, we need to do some User Mapping to make sure we understand the user issues

#### Acceptance Criteria

- [ ] User mapping is created for 'developers' 

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
