### ISSUE TITLE
Import data via an automated data management pipeline

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#18]
### User Story

In order to incorporate the Data lake store into my data management pipeline, as a LINZ developer, I want to import data into the Data Lake with an interface I automate (TBC).

#### Acceptance Criteria

- [ ] AWS data pipeline can validate data via a suitable interface (TBC)
- [ ] AWS data pipeline can receive useful information about validation via a suitable interface
- [ ] AWS data pipeline can store data in the Data Lake via a suitable interface
- [ ] Interface is based on LINZ/LI standards, if we have one
- [ ] Data is organised with a consistent structure for each dataset and each version (see HL design) *check which user story this should be in 

#### Additional context

Web API is out of scope for early delivery of this service.

Topographic Data team are planning to automate data management pipelines for Aerial and Historical Imagery in the near future (and probably other datasets later). They will be doing this in AWS using a (TODO: add detail) pattern for their data pipeline. See here for more information (TODO: add link to their design docs etc).

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
