### ISSUE TITLE
Prepare HL Design for presentation to ARB

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#19]
### Task

To raise visibility of the project with IS&D and ensure we have endorsement from LINZ corporate services, we should present the High Level design to the Architectural Review Board for endorsement.

#### Acceptance Criteria

- [x] Incorporate extra information that ARB needs, including conceptual diagram to help explain the Data Lake system (perhaps peer reviewed)
- [x] HL Design reviewed by other Solution Architects (Jeremy is potentially setting a working group to support this)
- [x] HL Design is reviewed by LINZ Information Architect
- [x] Privacy Threshold Assessment completed

#### Additional context

- Next ARB Meeting is 25 November, Papers are due Wed 18 Nov. Email Tracey + Brett to get added to the agenda. 
- Ivan to discuss with Jane. Jane working on lower level data architecture

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

### Tasks
- [x] Conceptual HL diagram
- [x] Aligning with ref architecture - review and adjust Bill's draft https://confluence.linz.govt.nz/display/LGDL/The+LINZ+Reference+Data+Architecture?src=contextnavpagetreemode
- [x] Security questions - answer in the HL Design  https://confluence.linz.govt.nz/display/LGDL/High+Level+Design#HighLevelDesign-OtherSecurityConsiderations
- [x] Add some words around support/maintenance adn operations (See comment) - https://confluence.linz.govt.nz/display/LGDL/High+Level+Design#HighLevelDesign-Support&Maintenance
