### ISSUE TITLE
Space to Store Topo Historic Imagery data

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#2]
### User Story

In order to store my important geospatial data, as a Topo Historic Imagery Data Manager, I want to store raw scanned historic imagery.

#### Acceptance Criteria

- [x] Store supports Tiff file format for data
- [x] Store supports JPEG file format for thumbnail (~200DPI) data
- [x] Store can scale to 200TB

#### Additional context

80 -> 200TB of un-georeferenced imagery scans (~700,000 files). There is no official spec for this, but can confirm with Topo team.
Users use WIN10 primarily.

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [x] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Detail Design
Purpose of this user story is to build S3 bucket storage with following configuration:

* S3 bucket name: `linz-geospatial-data-lake-prod` (prod env) and `linz-geospatial-data-lake-nonprod` (nonprod/test env)
* Storage class: S3 Intelligent-Tiering
* Versioning: enabled
* Access control: private
* Region: ap-southeast-2
* Removal policy: `RETAIN` (prod env), `DESTROY` (nonprod/test env)
* S3 bucket tags: `ApplicationLayer: data-lake-storage-bucket`, `EnvironmentType: prod/nonprod`
