### ISSUE TITLE
Create Metadata with CLI

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#20]
### User Story

In order to add metadata to my dataset, as a Data Maintainer, I want to create metadata with the CLI for my dataset

#### Acceptance Criteria

- [ ] User can create REQUIRED STAC metadata in the Data Lake
- [ ] User can create OPTIONAL STAC metadata in the Data Lake
- [ ] User can create custom metadata in the Data Lake

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
@jacobus I think it would be good to have this kind of use case for LINZ metadata editing? Basically some kind of API that can take some data assets, some file with some metadata some human specified metadata in it and then create fully compliant stac files. This would be useful for the geostore and is kind of how the data lake 2 and Topo Processor work. 

Does this fit in the catalogue work, or is it a different thing?

**Comment by billgeo** [comment]
Will raise new epics once metadata catalogue POC is completed.
