### ISSUE TITLE
Upload Metadata to staging bucket

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#21]
### User Story

Note: This is possibly solved by #9

In order to import my metadata into the Data Lake, as a Data Maintainer, I want to upload metadata to a staging bucket.

#### Acceptance Criteria

- [ ] Given when then

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
no longer required
