### ISSUE TITLE
Access for External Developers: User Mapping

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#22]
### User Story

In order to complete the user story for #6 and #7 we need to do some user mapping to understand the user issues we need to address.

#### Acceptance Criteria

- [ ] USer mapping completed

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
No longer needed. This was done as part of channels review.
