### ISSUE TITLE
Import metadata via an automated data management pipeline

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#23]
### User Story

In order to incorporate the Data lake store into my data management pipeline, as a LINZ developer, I want to import metadata in the Data Lake with a suitable interface (TBC).

### Acceptance Criteria
- [ ]  AWS data pipeline can validate metadata via a suitable interface (TBC)
- [ ]  AWS data pipeline can receive useful information about validation a suitable interface (TBC)
- [ ]  AWS data pipeline can store metadata in the Data Lake a suitable interface (TBC)
- [ ]  API is based on LINZ/LI standards (TBD)

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
