### ISSUE TITLE
Define Data Lake Product Key Performance Indicators

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#24]
### User Story

In order to make sure the product is achieving the benefits we intended, it is important to measure the performance of the product.

#### Acceptance Criteria

KPI - Key Performance Indicators

#### Tasks
- [x] Draft some KPIs
- [x] Workshop - Review with product team to ensure they are measurable
- [x] Finalise the KPIs.
- [x] Write user stories to implement any work we need to do

#### Additional context

Capture here: https://confluence.linz.govt.nz/display/LGDL/Product+KPIs+-+WIP

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Defined for now and created a new task to implement some kind of report or dashboard here: https://github.com/linz/geospatial-data-lake/issues/629
