### ISSUE TITLE
Create 'Dataset space' user interface

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#25]
### User Story

In order to store my data in the data lake, as a Data Maintainer (Historical Aerial Imagery), I want to create a 'dataset space' with a user interface so that I can import my data into data lake from a staging S3 bucket.

#### Acceptance Criteria

- [ ] Data Maintainer has an interface to create a 'dataset space' to import their data into

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
