### ISSUE TITLE
Create 'Dataset Space' endpoint

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#26]
### User Story

In order to organize my data, as a LINZ developer (for Historical Aerial Photos), I want to create a space for a 'dataset' so I can start importing data from my pipeline.

#### Acceptance Criteria

- [ ] Developer can invoke the process with the AWS CLI
- [ ] Dataset spaces persists
- [ ] Basic information about space is stored to enable user to distinguish between other datasets (see [HL](https://confluence.linz.govt.nz/display/LGDL/High+Level+Design) design) 
- [ ] Duplicate datasets are not allowed

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [x] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
