### ISSUE TITLE
LINZ Endorsement of High Level Design

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#28]
### Task

To raise visibility of the project with IS&D and ensure we have endorsement from LINZ corporate services, we should present the High Level design to the Architectural Review Board for endorsement.

#### Acceptance Criteria

- [x] Run through refgerence architecture alignment with stakeholders
- [x] Write memo for ARB
- [ ] ~~ Present to the ARB for endorsement ~~

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
