### ISSUE TITLE
Authentication of LINZ Users using AD

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#29]
### User Story

As a Data Owner, I want authentication of LINZ users (external users out of scope), so that only authorized users can access the data and metadata.

#### Acceptance Criteria

- [ ] LINZ Data Lake user is authenticated using LINZ AD credentials
- [ ] Authentication is implemented for DL python CLI
- [ ] User is identified via LINZ username and password
- [ ] Write access to any particular dataset is restricted to one or more AD groups
- [ ] Read access to all datasets is restricted to "all LINZ employees" AD group

#### Additional context

Single sign on is out of scope for now

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Closing. This has been done elsewhere.
