### ISSUE TITLE
Metadata import ('dataset version' end point)

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#3]
### User Story

In order to use my data effectively in the data lake, as a Data Maintainer, I want to import my dataset metadata with data from an s3 bucket and store it with my data in the 'dataset version'.

#### Acceptance Criteria

- [ ] Metadata can be imported from any custom s3 bucket where Data Lake has read permissions
- [ ] Correct metadata is mandatory for dataset version creation

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
