### ISSUE TITLE
Authorization of LINZ Users - using AD

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#30]
### User Story

As a Data Owner, I want data readable by any LINZ data analyst and allow write access only for my Data Maintainers, so that only authorized users can access the data and metadata.

#### Acceptance Criteria

- [ ] Authorization is by LINZ managed AD groups
- [ ] Write access to any particular dataset is restricted to one or more AD groups
- [ ] Read access to all datasets is restricted to "all LINZ employees" AD group

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
