### ISSUE TITLE
Create 'Dataset Space' user interface

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#31]
### User Story

In order to organize my data, as a Data Maintainer (for Historical Aerial Photos), I want to create a space for a 'dataset' so I can start importing data from my pipeline.

#### Acceptance Criteria

- [ ] Data Maintainer is able to create a new dataset space using a python CLI
- [ ] Dataset spaces persists
- [ ] Basic information about space is stored to enable user to distinguish between other datasets (see [HL](https://confluence.linz.govt.nz/display/LGDL/High+Level+Design) design) 
- [ ] Duplicate datasets are not allowed

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
