### ISSUE TITLE
Sprint 1 Retro Actions

### ISSUE THREAD

**Issue by JoCaudwell** [linz/geospatial-data-lake-team#33]
This EPIC covers the next steps agreed at the sprint 1 retrospective to be completed in sprint 2. 

Tasks:

- [x] Clarify Jeremy's role and involvement in the project
- [x] Get help with splitting user stories
- [x] Flag resource issue and slowdown of project to LILT
- [x] Change sprint scheduling so LILT can attend
- [x] Add regular calendar item to test upcoming user stories with the users 
- [x] add 'review user story with a user' to definition of ready
