### ISSUE TITLE
define data validation checks ('dataset version' end point)

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#37]
### User Story

In order to make sure my data is not corrupted, as a Topo Historic Imagery Data Maintainer, I want to define the data validation checks that are performed on my data while creating a dataset version.

#### Acceptance Criteria

- [x] Mandatory data validation checks are defined in documentation  - https://confluence.linz.govt.nz/pages/viewpage.action?pageId=83655473

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [x] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
