### ISSUE TITLE
Basic AWS authorization

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#39]
### User Story

In order to ensure only authorized users can access or edit the data, as a Data Manager, I want to have assurance that users are reliably authenticated and have appropriate authorization according to their role.

#### Acceptance Criteria

- [ ] Only authenticated Administrators (with an AWS account and in the 'Data Lake admin' AD Group) can administer the system
- [ ] Only authenticated Data Maintainers (with an AWS account and in the relevant 'Dataset Maintainer' AD Group) can write/create, edit or delete/archive from the store
- [ ] User uses existing AWS authentication tools to authenticate
- [ ] All other users will not have access

#### Additional context

User will need to have an AWS account
Current AD groups for AWS https://confluence.linz.govt.nz/display/PuC/AWS+Azure+AD+Access+Control
Can also use LDS Groups as a template to start with. e.g. https://data.linz.govt.nz/manage/groups/2115/users/

#### Tasks
- [ ] Create roles that can be assumed
- [ ] Determine how to assume roles from AD groups (advice from others at LINZ)
- [ ] Setup any new AD Groups needed - `Data Lake Data Maintainers`
- [ ] Create test AD user
- [ ] Connect AD Groups to Data Lake roles

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
