### ISSUE TITLE
Security signoff

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#40]
### Task

In order to ensure the product is secure and meets LINZ's enterprise standards for security, we need to go thorgh the LINZ C&A process (or "C&A Light"). 

#### Acceptance Criteria

- [ ] Data Lake product is certified by LINZ security before the first release.

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
