### ISSUE TITLE
Basic CLI user interface (non-interactive)

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#41]
### User Story

So that I can manipulate assets and metadata, as a dataset maintainer, I want to have a simple CLI instead of having to talk to the API directly.

#### Acceptance Criteria

- [x] Given the user is on WSL2 within Windows, when trying to install and run the CLI, then it should succeed
- [x] When running the CLI without any parameters, then it _either_ explains directly how to run it or tells the user which command to run to find out how to run it
- [x] When a CLI command fails for a known reason, a short, user friendly message should be shown. Such failures include at least missing credentials and wrong command syntax.
- [x] When a CLI command fails for an unknown reason, then the error message should be shown verbatim
- [x] When a CLI command succeeds, then only new information should be printed (that is, we should not repeat the input parameters)
- [x] Support all the existing API endpoint interactions

#### Tasks

- [x] Document CLI install prerequisites (`pip`)
- [x] Document CLI runtime prerequisites (valid AWS credentials)
- [x] Document how to install the CLI
- [x] Return 0 on success, and consistent non-0 exit codes on errors (investigate what the `aws` command does, and maybe copy it?)
- [x] Push program to LINZ PyPI account so it can be installed by anyone
- [x] Document PR review guidelines for CLI-related code
- [x] Resolve [missing runtime dependencies in package](https://stackoverflow.com/q/69763090/96588)
- [x] Set up easy version bumping. Provided by `poetry version patch` etc.
- [x] Set up automated build when pushing PRs or to the main branch
- [x] Enforce successful build before merging PRs
- [x] Enable specifying environment name as a parameter

#### Guidelines

- Should be a thin layer on top of the existing Lambdas, to keep it simple
- Should be non-interactive, to allow scripting and keep it simple.
- Should support all API functions of the Data Lake.
- Should be designed for someone who has a basic knowledge of using the command line in Linux

[Nice-to-haves](https://github.com/linz/geostore/issues/1146) have been relegated to a separate issue.

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Tested yesterday and the basic CLI looks good. I have a list of potential things to improve.
