### ISSUE TITLE
Support for LDS 'S3 data source'

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#44]
### User Story

In order to configure an LDS 'source' and extract data from the Data Lake, as a Data Maintainer, I want to set up an LDS 'S3 source' and 'scan' the source to import the data into the LDS.

#### Acceptance Criteria

- [x] A dataset space can be set up as a 'source' on the LDS
- [x] Dataset space can be 'scanned' by the LDS (permissions etc)
- [x] Data is successfully imported into the LDS
- [x] Metadata is successfully imported into the LDS
- [ ] When the dataset is updated or edited, the LDS successfully scans and imports changed data

#### Additional context

Koordinates spec/requirements for an S3 source are here: https://help.koordinates.com/import-data/import-data-amazon-s3-web-console/
Metadata is currently only ISO-19115 format

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Tasks

- Design s3 bucket structure to support LDS
- Setup permissions for LDS
