### ISSUE TITLE
Support Basemaps pulling data

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#45]
### User Story

In order to publish a LINZ 'basemap', as a LINZ Developer, I want to extract data from the Data Lake into the Basemaps system.

#### Acceptance Criteria

- [ ] Given any dataset in the Data Lake, when the Basemaps system attempts to access the dataset files (data and metadata) via S3 API, then the Basemaps system can access and extract the data and the metadata

#### Additional context

Basemaps system is here: 

- S3 API to read access for single directory with all data in it
- The script to import imagery is here. It searches the bucket for a directory with the supplied value and then attempts to process all the geotiffs in that directory. https://github.com/linz/basemaps-team/tree/master/packages/import-imagery

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Done. S3 api covers this.
