### ISSUE TITLE
Spike: lambda Step functions

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#47]
### Tasks

In order to estimate #4 properly we need to do some learning about Lambda step functions

#### Acceptance Criteria

- [x] We have information required to estimate #4 better
- [ ] Findings are documented in Confluence
- [ ] ...

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
