### ISSUE TITLE
Onboard Victor on the Data Lake

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#48]
### Task

Onboard Victor to the DL so he can start working on development tasks

#### Acceptance Criteria

- [x] Victor has reviewed the DL and has most of the information he needs to get started
- [x] Victor has access to everything he needs
- [x] Victor is invited to all meetings etc.

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
