### ISSUE TITLE
Create test datasets for development and testing

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake-team#49]
### Tasks

So that we can write quality automated tests we need test datasets.

#### Acceptance Criteria

- [ ] Small test aerial imagery dataset (including STAC metadata) is created in S3 bucket
- [ ] Large test aerial imagery dataset (including STAC metadata) is created in S3 bucket
- [ ] Small historic imagery dataset (including STAC metadata) is created in S3 bucket

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
