### ISSUE TITLE
Validate metadata  ('dataset version' end point)

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#5]
### User Story

In order to make sure my metadata has the mandatory information to make it usable later, as a Topo Historic Imagery Data Manager, I want to validate my metadata during dataset version creation.

#### Acceptance Criteria

- [x] Given a metadata file which does not fit the hierarchical STAC/JSON standard, when the user creates a dataset version, then the system should halt the creation process
- [ ] ~~Given a metadata file, when the user creates a dataset version, then the validation results should be stored permanently~~
- [x] Given a metadata file, when 'required' metadata elements are missing, then the system should halt the creation process
- [x] Given a collection metadata file, when a child file is unreadable, the system should halt the process

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
