### ISSUE TITLE
Get import status (dataset version endpoint)

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#55]
### User Story

In order to manage my dataset effectively, as a Topo Developer, I want to know the status of the data import and validation.

#### Acceptance Criteria

- [ ] Given a dataset version has been started, When the status of the dataset version creation is requested, the status and reasonable detail is returned.
- [ ] Given a request for a status, when the dataset version doesn't exist, then a suitable error message is returned.

### Tasks
- [ ] Return whether the state machine is done yet
- [ ] Return which state of the state machine we are at currently
- [ ] Optionally return all failed validation results including error results. 
- [ ] (add to separate story) add more detail to when we store error results in table; timestamp, request ID, API version
- [ ] Communicate what the full response will look like with Bill

#### Additional context

- 'Reasonable' is a bit vague, but can be tested with Product Owner and users if needed.

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
