### ISSUE TITLE
CLI support mutliple environments

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#56]
### User Story

In order to create, edit or delete/archive my data/metadata, as a Data Maintainer, I want a basic CLI to interact with the data lake

#### Acceptance Criteria

- [ ] A basic CLI can be installed on a Data Maintainers preferred environment (split to another story)
- [ ] User friendly installer (split to another story)

#### Additional context

Data Maintainers will want to use the CLI in a variety of environments such as WIN10, Linux and AWS Workspaces.

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
