### ISSUE TITLE
Sprint 4 Retro actions

### ISSUE THREAD

**Issue by JoCaudwell** [linz/geospatial-data-lake-team#57]
#### Additional context
Action points from the sprint 4 retro 

#### Tasks
- [x] increase collaboration with Topo - Victor to help facilitate discussion @l0b0 ( @billgeo to help facilitate)
- [x] more small spikes for new tech @imincik @l0b0 @billgeo (think about some useful spikes before backlog refinement)
- [x] try other retro format @JoCaudwell (format set up. Complete)
