### ISSUE TITLE
Finish design for data processing pipeline

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#58]
### Task

In order to deploy code processing data, we need a design for a pipeline that is well tested and confirem want to [do something].

#### Acceptance Criteria

- [ ] Finish the design that was started in the last sprint
- [ ] Have any relevant discussions with others working on similar designs and records any decisions

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
