### ISSUE TITLE
Kibana POC: Develop basic browse/filter/search Metadata

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#59]
### User Story

In order to provide feedback on how I can find and understand the data I want to use, as a Data Analyst or Developer, I want a POC showing a basic metadata browser/filter/search and appraise the get the data I want

Note: previous spike identified Elasticsearch and Kibana (test Elasticmaps later) as the tech to use for the POC. See here: https://confluence.linz.govt.nz/display/LGDL/STAC+Browser+Investigation

And the typical user flow: https://confluence.linz.govt.nz/display/LGDL/User+Flows#UserFlows-FindData-FutureState

Additional questions to answer in POC:

- Can we get analytics on filter/queries done by ysers on Kibana?
- Can we customise the map, adding in LINZ basemaps?
- How do we give easy access to all LINZ Data Analysts (e.g. embed the UI in some LINZ webpage?)
- Is the UI simple enough to use for LINZ Data Analysts?
~~- split into separate story - Would elastic maps be better than Kibana?~~
- Show some real LINZ metadata

#### Acceptance Criteria

- [ ] Given I don't know what data I want, when I open the tool, I can start filtering/searching/browsing the metadata
- [ ] Given I know the title or part of the title of the data I want, when I open the tool, I can add a filter(s) with the information I have and it return the datasets with that text (case insensitive) in the title
- [ ] Given that I am only interested in the latest version of a dataset, when do any kind of filter/search, I can easily include a filter that returns only the latest versions of the datasets
- [ ] Given I only want datasets in a certain group(s) (e.g. Aerial Imagery, LiDAR, Historic Imagery), when I do any kind of filter/search, I can easily include a filter that return only the datasets of the group(s) I have specified.
- [ ] Given I don't know what types of metadata LINZ has, when I start the tool, then there is a list of common filter/metadata elements that I can use
- [ ] Given that I have identified a dataset that I am interested in, when I select it, then I can easily get the location of the data assets (or links / supplementary files) for the dataset so I can retrieve them
- [ ] Given that I don't know what data to search for, when I start the tool, then there is a list of pre-built popular filter queries that I can use
- [ ] Given that the metadata has a bounding box, when I browse or inspect a dataset(s), then I can see it on a map
- [ ] Given that the data has other (text and numbers etc) metadata, when I browse multiple datasets, then I can easily see a table of datasets with some useful metadata displayed (e.g. title, description etc)
- [ ] Given that there are multiple assets/items for a dataset, then I can drill down to those items and view the metadata for that item.
- [ ] Given that the metadata has a thumbnail, when I browse or inspect a dataset(s), then I can see the thumbnail (is this a thing?)

#### Tasks

- [x] find four representative and diverse users
- [x] document workshop processs/agenda
- [x] gather some scenarios to use in the workshop
- [x] give access to workshop users
- [x] workshop a strawman kibana dashboard with PO
- [x] workshop kibana dashboard with users,
       suggested users: Andrew Ferrel, Emory Beck, Vicki, Bradley Cooper
- [x] Document feedback that we can turn into backlog issues
- [ ] Demo with Geostore team and decide on next steps 5

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
@l0b0 - could you add the information you found last week about STAC browsig to this issue? Would suggest a confluence page with the outcome of the research.

**Comment by billgeo** [comment]
Hey @MitchellPaff here's a list of pre-canned filters that would be useful I think (as a starting point).

##### Data 'Groups' similar to what's on the LDS
- All datasets with the phrase 'Aerial Photos' in the title (filter can be labelled 'Aerial Photos')
- All datasets with the phrase 'LiDAR' in the title (filter can be labelled 'Elevation')
- All datasets with the phrase 'Landonline:' at the start of the title (filter can be labelled 'Landonline')
- All datasets with the phrase 'Chart' in the title (filter can be labelled 'Hydrographic Charts')
- All datasets with the phrase 'Topo' in the title (filter can be labelled 'Topographic')

Will send some more soon...

**Comment by billgeo** [comment]
Created #931 to work on the feedback. Closing.

Feedback is capture here:
https://linzsrm.sharepoint.com/:x:/s/Geo-spatialDataLake/EUWTmsEAAhhEmPz1Dub_-ZcByhD2yj_gd3QkOT_5hxofFw?e=5DwRmn
