### ISSUE TITLE
Access for External Developers

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#6]
### User Story

In order to use LINZ data in my application or analysis pipeline, as a External Developer, I want to access data directly from the Data Lake, instead of by courier from the LINZ Data Service (datasets greater than 4GB)

#### Acceptance Criteria

- [ ] User has temporary access to data they have been granted access to (TODO: confirm if user needs permanent access)
- [ ] User can request access to a dataset
- [ ] User can not access any other data that they haven't been granted access to
- [ ] LINZ can grant or refuse access

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Duplicate.
