### ISSUE TITLE
Verify dataset space exists (dataset version endpoint)

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#60]
### User Story

In order to store my data in the data lake successfully, as a Data Maintainer, I want to know if my dataset space doesn't exist yet.

#### Acceptance Criteria

- [ ] Given I have launched a dataset import (dataset version creation), when the dataset space ID I have supplied doesn't exist, then I should get an error message.

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
