### ISSUE TITLE
Windows CLI

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#61]
### User Story

In order to use the Data Lake, as a Hydro Data Maintainer, I want to use the CLI on my LINZ WIN10 machine

#### Acceptance Criteria

- [ ] Given when then

#### Additional context

This story could be handled by Windows Subsystem for Linux which should be installed on LINZ laptops?

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Duplicate
