### ISSUE TITLE
Search metadata

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#62]
### User Story

In order to find the data I want to use, as a Data Analyst or Developer, I want to search the data lake metadata.

#### Acceptance Criteria

- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]
- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]

#### Tasks

- [ ] Index the entire metadata catalogue
- [ ] Provide a way to search the index

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Now part of metadata catalogue POC work. Will raise new epics from that POC.
