### ISSUE TITLE
Implement copy data/metadata functionality

### ISSUE THREAD

**Issue by JoCaudwell** [linz/geospatial-data-lake-team#69]
### User Story

So that the data is stored in the Data Lake, as a Data Maintainer, I want the data lake to copy data and metadata from it's current S3 source to the Data Lake at the end of the import process.
 

#### Acceptance Criteria

- [ ] Given any list of dataset and metadata, when import is triggered, then the data lake copies the data and metadata across to data/metadata lake s3 bucket.

#### Potential tasks from planning discussion
- [x] Create lambda function to use S3 Batch Operations with list of files to be transferred, as last step in Step function 
- [x] Add this step in Step function to infrastructure using CDK 
- [x] Store result (specify) of S3 Batch Operation (PUT operation) in target S3 bucket, but don't do anything with results (yet).
- [x] Add required S3 Batch Operations permissions
- [x] implement logging in the task
- [x] write functional and logging tests for import dataset task

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Subtasks

- Test AWS Batch Copy and confirm we want to use it
