### ISSUE TITLE
Subscribe to notifications about new or updated data

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#7]
### User Story

In order to know about data I can use in my application or analysis pipeline, as a Developer or Data Analyst, I want to subscribe to notifications about new data or updates to data I am interested in.

#### Acceptance Criteria

- [ ] Given a , when then

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
dupe of #560 which is better described
