### ISSUE TITLE
Extend metadata validation for 'LINZ required' metadata

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#75]
### User Story

So that I can be confident that my metadata is correct, as a Data Maintainer, I want to validate my metadata against the LINZ required metadata elements (to be defined).

#### Acceptance Criteria

- [ ] Given I have requested a new dataset version, when my metadata is missing a 'LINZ required' metadata element (to be defined), then I want the new dataset version aborted and to receive a reason why.

#### Additional context

May require storing the version of the software and validation that was used to import a dataset

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Done
