### ISSUE TITLE
Complete security risk register

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#76]
### Chore

So that we can have the system certified by security, we need to complete a security risk register completed that can go into the security certification.

#### Acceptance Criteria

- [x] Security risk review completed
- [x] Med/High risks moved to main risk register
- [x] Backlog items created for outstanding mitigations
- [x] Security risk review shared with IS&D security team

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [x] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
