### ISSUE TITLE
Update docs on how to manage secrets

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#85]
### Enabler

So that we can reduce risk SR09 (secrets are lost and recovery is delayed), we want to document the process for retrieving and restoring secrets

#### Acceptance Criteria

- [x] Documented processes on how to manage, retrieve and refresh secrets, with examples
- [x] Secrets can be recovered easily by anyone in the product team
- [x] Secrets are not included in logs, which means that we should not log requests verbatim
- [x] Secrets *may* be readable and writable by the entire team
- [x] Secrets are not included in the GDL repository (this includes encrypted files, because of the risk of weak encryption)
- [ ] ~~Secrets can have fine-grained access controls (e.g. backup credentials stored separately from other credentials, accessible by only a subset of the team)~~

#### Additional context
[GitHub secrets](https://github.com/linz/geospatial-data-lake/settings/secrets/actions):

- AWS_ACCESS_KEY_ID (could just regenerate these instead of storing)
- ~~AWS_ASSUME_ROLE_CI (could hard code these so they never change)~~
- ~~AWS_ASSUME_ROLE_NON_PROD (could hard code these so they never change)~~
- ~~AWS_ASSUME_ROLE_PROD (could hard code these so they never change)~~
- AWS_SECRET_ACCESS_KEY (could just regenerate these instead of storing)
- ~~DATALAKE_USERS_AWS_ACCOUNTS_IDS_NON_PROD (these might be removed after authorization story)~~
- ~~DATALAKE_USERS_AWS_ACCOUNTS_IDS_PROD (these might be removed after authorization story)~~

Other secrets:

- TBC: backup account access/secret key

#### Tasks

- [ ] Determine best place to store secrets that everyone in the team can access and update. Suggestions:
   - ~~KeePass file stored on LINZ intranet so that it's only accessible by GDL team members.~~
   - ~~LastPass shared secrets (according to some people at LINZ this doesn't work as well as expected). (Could use this if it works?)~~
   - ~~AWS Secret storage (preferred for sensitive info)~~
   - If there's no sensitive info just put it in Git repo. 
- [x] Document processes according to the above

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by l0b0** [comment]
Documentation started at https://confluence.linz.govt.nz/display/LGDL/Secrets+management; will need to be filled in by Ivan or someone else who knows which account/role we use for the AWS credentials.

**Comment by imincik** [comment]
Secrets `DATALAKE_USERS_AWS_ACCOUNTS_IDS_{NON_PROD,PROD}` are not needed anymore and where deleted from GitHub secrets.

**Comment by imincik** [comment]
@billgeo , documentation is finished and tested.
