### ISSUE TITLE
Spike: how will we implement PITR for S3?

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#86]
### Enabler

So that we can decide how to do a point in time restore for data in a AWS S3, we want to research all the options and methods available.

#### Acceptance Criteria

- [ ] We can estimate story #42 accurately, and split it into small chunks (< 8 epic points)
- [ ] We can break down #42 into tasks
- [ ] Any remaining assumptions are noted and estimated for impact on delivering the story

#### Tasks

- [ ] Research possible methods for PITR on S3
- [ ] Do any POCs needed to test thinking and assumptions

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Closing this after discussion with Terence last week. Decided we won't do Backup and Restore now.
