### ISSUE TITLE
Spike: how should we store backups in a separate account?

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#87]
### Enabler

So that backups can be stored securely, we want to learn how best to store backups in a separate AWS account and then retrieve them later for a restore

#### Acceptance Criteria

- [ ] We can break story https://github.com/linz/geospatial-data-lake-team/issues/42 down into tasks without significant assumption, and split it into small chunks (< 8 epic points)
- [ ] We are confident in the estimate of https://github.com/linz/geospatial-data-lake-team/issues/42 
- [ ] Any remaining assumptions are noted and considered for the the estimate

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Hi @imincik do we still need this spike after you research the other day? Or if we do, can you re-estimate it please.

**Comment by billgeo** [comment]
Closing this after discussion with Terence last week. Decided we won't do Backup and Restore now.

**Comment by imincik** [comment]
I confirm this spike is not needed
