### ISSUE TITLE
Upload data to AWS staging bucket

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake-team#9]
### User Story

In order to store my data, as a Data Maintainer, I want to upload to a place where the data lake can access it (AWS cloud) 

#### Acceptance Criteria

- [ ] Data Maintainer can upload data to a staging bucket

#### Additional context

80 -> 200TB of un-georeferenced imagery scans (~700,000 files). There is no official spec for this, but can confirm with Topo team.
Users use WIN10 primarily.

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
No longer needed.
